import "./globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import SideBar from "./sidebar/SideBar";
import { InvoiceProvider } from "@/lib/store/invoice-context";

const inter = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <InvoiceProvider>
      <html lang="en">
        <body className={inter.className}>
          <SideBar />
          <main className="m-middle sm:my-24 max-w-default w-3/4">
            {children}
          </main>
        </body>
      </html>
    </InvoiceProvider>
  );
}
