import "./globals.css";
import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import SideBar from "./SideBar";

const inter = League_Spartan({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        <main className="m-middle w-default">
          {children}
        </main>
      </body>
    </html>
  );
}
